Morningstar/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page

from Morningstar.settings.common import CACHE_TIMEOUT
from Morningstar.settings.common import MEDIA_ROOT


from .views import dev, info, shortcut, tool

from .sitemaps import Sitemaps


urlpatterns = [
    # 工具
    path('get-image-captcha/',tool.get_image_captcha, name="get_image_captcha"),
    path('activate-by-email/', tool.activate_by_email, name="activate_by_email"),
    path('send-phone-code/<slug:template>/', tool.send_phone_code, name="send_phone_code"),
    path('send-email-code/<slug:template>/', tool.send_email_code, name="send_email_code"),
    path('get-login-token/<slug:identity>/', tool.get_login_token, name="get_login_token"),
    path('login-by-token/<str:token>/', tool.login_by_token, name="login_by_token"),
    # 开发
    path('dev/info/', dev.info, name="dev-info"),
    path('dev/map/', dev.map, name="dev-map"),
    # 信息
    path('me/', cache_page(CACHE_TIMEOUT)(info.me), name="me"),
    path('sitemap.xml', cache_page(CACHE_TIMEOUT)(sitemap), {'sitemaps': Sitemaps},name='sitemap'),
    path("credits/", cache_page(CACHE_TIMEOUT)(info.credits), name="credits"),
    path("favicon.ico", cache_page(CACHE_TIMEOUT)(info.get_favicon), name="favicon"),
    path("qrcode/", cache_page(CACHE_TIMEOUT)(info.get_qrcode), name="qrcode"),
    path("robots.txt", cache_page(CACHE_TIMEOUT)(TemplateView.as_view(template_name="base/robots.txt", content_type="text/plain"))),
    # 应用
    path('', include('blog.urls')),
    path('book/', include('book.urls')),
    path('formula/', include('formula.urls')),
    path('game/', include('game.urls')),
    path('joke/', include('joke.urls')),
    path('lover/', include('lover.urls')),
    path('nav/', include('nav.urls')),
    path('poll/', include('poll.urls')),
    path('proxy/', include('proxy.urls')),
    path('rss/', include('rss.urls')),
    path('share/', include('share.urls')),
    # 快捷
    path('shortcut/<slug:name>/', cache_page(CACHE_TIMEOUT)(shortcut.shortcut), name="shortcut"),
    # 调试
    path('debug/', include('debug_toolbar.urls')),
    # 媒体
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT}),
    # 管理
    path('admin/', admin.site.urls, name="admin"),
    # restful api
    path('api-auth/', include('rest_framework.urls'))
]

apps/book/urls.py
from django.urls import path
from Morningstar.settings.common import CACHE_TIMEOUT
from django.views.decorators.cache import cache_page

from . import views


app_name = 'book'
urlpatterns = [
    path('', cache_page(CACHE_TIMEOUT)(views.IndexView.as_view()), name="index"),
    path('api/', cache_page(CACHE_TIMEOUT)(views.BookListView.as_view()), name="api"),
]

apps/book/models.py
from django.db import models
from requests.utils import unquote

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        app_label = 'book'

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = '作者'
        verbose_name_plural = verbose_name
        app_label = 'book'

    def __str__(self):
        return self.name


class Translator(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = '译者'
        verbose_name_plural = verbose_name
        app_label = 'book'

    def __str__(self):
        return self.name


class Book(models.Model):
    book_name = models.CharField('书名', max_length=100)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    author = models.ForeignKey(Author, verbose_name='作者', on_delete=models.SET_DEFAULT, null=True, default=None)
    translator = models.ForeignKey(Translator, verbose_name='译者', on_delete=models.SET_DEFAULT, null=True, default=None, blank=True)
    file = models.FileField('文件', upload_to="book/%Y%m%d%H%M%S/", default="book/default.pdf", blank=True, null=True)
    foreign_url = models.URLField('外链', null=True, blank=True)

    @property
    def uri(self):
        return unquote(self.foreign_url if self.foreign_url else self.file.url)

    class Meta:
        verbose_name = '书目'
        verbose_name_plural = verbose_name
        app_label = 'book'

    def __str__(self):
        return self.book_name

apps/book/forms.py
from django import forms
from captcha.fields import ReCaptchaField

class VerifyForm(forms.Form):
    captcha = ReCaptchaField(label="人机验证")

apps/book/views.py
import json
import os

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, reverse
from django.views import View

from rest_framework.views import APIView
from rest_framework.response import Response

from Morningstar.views.base import fix_fetched_post
from .models import Book
from .serializers import BookSerializer
from .forms import VerifyForm


class IndexView(View):
    def get(self, request):
        def get_endpoint(request):
            protocol = "https://" if os.environ.get('DJANGO_SETTINGS_MODULE', 'Morningstar.settings.dev') == 'Morningstar.settings.production' else "http://"
            endpoint = protocol + request.get_host() + reverse("book:api")
            return endpoint
        verify_form = VerifyForm()
        books = Book.objects.all()
        endpoint = get_endpoint(request)
        return render(request, "book/index.html", locals())

    def post(self, request):
        request = fix_fetched_post(request)
        form = VerifyForm(request.POST)
        if form.is_valid():
            book = Book.objects.get(id=int(request.POST["bookId"]))
            return JsonResponse({
                "status": "success",
                "book_name": book.book_name,
                "author": book.author.name,
                "uri": book.uri,
            })
        else:
            return JsonResponse({"status": "failure"})


class BookListView(APIView):
    def get(self, request):
        book_serializers = BookSerializer(Book.objects.all(), many=True)
        return Response(book_serializers.data)

apps/book/templates/book/index.html
{% load compress %}
{% load matomo_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=350">
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
	<link rel="icon" href="{% static 'book/img/favicon.ico' %}">
	<link rel="apple-touch-icon" href="{% static 'book/img/favicon.png' %}">
	<!--https://fontawesome.com/v6/icons?m=free-->
	<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{% static 'node_modules/pace-js/pace-theme-default.min.css' %}">
	<script src="{% static 'node_modules/pace-js/pace.min.js' %}"></script>
	<title>Book - 我的书单</title>
	<meta name="description" content="时不时会分享刚读完的好书">
	{% compress css %}
	<link rel="stylesheet" href="{% static 'book/css/base.css' %}">
	{% endcompress %}
	{% tracking_code %}
</head>

<body>
	<div class="modals">
		<div>
			<input type="checkbox" id="my-modal" class="modal-toggle" />
			<div class="modal">
				<div class="modal-box relative p-8" id="myModalBox">
					<label for="my-modal" class="btn btn-sm btn-circle absolute right-2 top-2"
						id="myModalToggle">✕</label>
					<div class="text-4xl text-center font-bold">下载</div>
					<form action="{% url 'book:index' %}" method="POST" class="mt-5">
						{% csrf_token %}
						{{ verify_form.captcha }}
						<style>
							.g-recaptcha {
								display: flex;
								justify-content: center;
							}
						</style>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="min-h-screen container mx-auto">
		<header class="flex space-x-2 justify-center items-center text-3xl md:text-4xl pt-6">
			<span class="">我的书单</span>
			<i class="fa-brands fa-searchengin cursor-pointer" id="searchButton"></i>
		</header>
		<main class="overflow-x-auto mt-4 mb-8 relative">
			<table class="table table-zebra w-full">
				<thead>
					<tr>
						<th class="text-lg">编号</th>
						<th class="text-lg">书名</th>
						<th class="text-lg">分类</th>
						<th class="text-lg">作者</th>
						<th class="text-lg">译者</th>
						<th class="text-lg">下载</th>
					</tr>
				</thead>
				<tbody>
					{% for book in books %}
					<tr>
						<th>{{ forloop.counter }}</th>
						<td class="font-bold">{{ book.book_name }}</td>
						<td>{{ book.category.name }}</td>
						<td>{{ book.author.name }}</td>
						<td>
							{% if book.translator.name %}
							{{ book.translator.name }}
							{% else %}
							<span>/</span>
							{% endif %}
						</td>
						<th>
							<label for="my-modal" class="modal-button" data-bookId="{{ book.id }}">
								{% if book.foreign_url %}
								<div class="text-lime-500">外链下载</div>
								{% else %}
								<div class="text-red-500">站内下载</div>
								{% endif %}
							</label>
						</th>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</main>
		<footer class="mb-2">
			<div class="text-center">
				<div id="runtime_span"></div>
				<div id="copyright">
					<span>© 2022
						<a href="{% url 'me' %}" class="font-bold" style="font-family: Lora">Henry Ji</a>
					</span>
					<span class="brightness-0">/</span>
					<span>License: <a href="https://www.gnu.org/licenses/agpl-3.0.en.html"
							class="font-bold">AGPLv3</a></span>
					<span class="brightness-0">/</span>
					<span>Powered by <a href="https://www.djangoproject.com/" class="font-bold">Django</a></span>
				</div>
			</div>
			{% compress js %}
			<script src="{% static 'base/js/runtime.js' %}"></script>
			{% endcompress %}
		</footer>

	</div>

	<div id="overlay" class="hidden w-screen h-full z-40 absolute top-0 bg-gray-400/50">
		<div class="w-screen z-50 fixed top-[4rem] md:top-[7rem]" onclick="event.stopPropagation()">
			<form class="max-w-3xl md:max-w-2xl mx-auto px-8">
				<input type="text" placeholder="书名/作者" id="searchInput"
					class="w-full p-4 text-center text-2xl md:text-3xl rounded-3xl outline-none border-solid border-slate-300 border-8">
				<ul class="w-full px-4" id="suggestionList">
					<li class="p-4 text-gray-400">这里会显示推荐的书目</li>
				</ul>
			</form>
		</div>
	</div>
</body>

<script src="{% static 'node_modules/canvas-nest.js/dist/canvas-nest.js' %}"></script>
<script data-href="https://github.com/HenryJi529/OpenMorningstar"
	src="{% static 'node_modules/github-corners/dist/embed.min.js' %}"></script>

<script>
	const csrfToken = "{{ csrf_token }}";
	const endpoint = "{{ endpoint }}";
	const verifyUrl = "{% url 'book:index' %}";
	document.querySelector("#searchButton").addEventListener('click', e => {
		document.querySelector("#overlay").classList.remove("hidden");
	})
	document.querySelector("#overlay").addEventListener('click', e => {
		document.querySelector("#overlay").classList.add('hidden');
	})
</script>

{% compress js %}
<script src="{% static 'book/js/search.js' %}"></script>
<script src="{% static 'book/js/verify.js' %}"></script>
{% endcompress %}

</html>